kramdown:
  input:  GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Zero
tagline:          'A Jekyll theme'
description:      '从零开始的游戏开发'
url:              http://hyde.getpoole.com
baseurl:          /


paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/OhZero

gems: [jekyll-paginate]